

# --------------------------------
# BASE

server:
  port: 17082
  servlet.context-path: /v0.6


spring:
  profiles.active:
  - proj-default
  #- proj-air
  - proj-pro
  #- proj-aws
  #- proj-dfep
  #- proj-real
  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost:9092/sentbedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate.jdbc.time-zone: UTC+9
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 50
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  servlet.multipart:
    enabled: true
    location: ~/FILES
    max-file-size: 5GB
    max-request-size: 5GB
  devtools:
    livereload.enabled: true


logging:
  file:
    path: logs/link/
    max-size: 10MB
    max-history: 30         # delete after a month
  pattern:
    console: "%clr(%d{HH:mm:ss} %p){magenta} - %m%n"
    file: "%d %-5level [%-10thread] [%-30logger{30}] - %m%n"
  level:
    root: info
    org.tain.*: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.thymeleaf: info
    org.h2.server.web: info
    
    #org.tain.utils.TransferStrAndJson: trace
    org.tain.utils.LnsSentbeClient: trace


---
# --------------------------------------------------------
spring.profiles: proj-default

proj-env:
  base:
    name: Sentbe API project
    program: KieaSentbe API program
    version: ver 0.5_2020.09.23
    comment: This is Sentbe API project.
  param:
    name: PARAM (default)
  job:
    name: JOB (default)
  json:
    name: JSON (default)
  url:
    name: URL (default)

---
# --------------------------------------------------------
# proj-local
spring.profiles: proj-air

proj-env:

  param:
    name: PARAM (air)
    sentbe-client-key: Jien4aeyae7ohjeithahM9ja7quowua4
    sentbe-secret-key-for-data: cXdqZmlvcWVqd2xd2pmam9pZaG9nZnFl
    sentbe-secret-key-for-hmac: 6fc1bf16f3cb6f5b6a1044fd9edecba9722014489c39a7d16ad7b9961aea770b9cd0e3e4a85510bba0dd97e6d6aac884d910e6384c7b76df992deece5cb57a78
    home: /Users/kang-air
    base: /KANG/sentbe/20201010
    info-path: /jsonInfo
    data-path: /jsonData
  job:
    name: JOB (air)
  json:
    name: JSON (air)
    error-info-file: error.json
  url:
    name: URL (air)
    sentbe: http://localhost:17080/v0.6
    #sentbe: https://hanwha.dev.sentbe.com:10443

---
# --------------------------------------------------------
# proj-test
spring.profiles: proj-pro

proj-env:

  param:
    name: PARAM (pro)
    sentbe-client-key: Jien4aeyae7ohjeithahM9ja7quowua4
    sentbe-secret-key-for-data: cXdqZmlvcWVqd2xd2pmam9pZaG9nZnFl
    sentbe-secret-key-for-hmac: 6fc1bf16f3cb6f5b6a1044fd9edecba9722014489c39a7d16ad7b9961aea770b9cd0e3e4a85510bba0dd97e6d6aac884d910e6384c7b76df992deece5cb57a78
    home: /Users/kangmac
    base: /KANG/sentbe/20201010
    info-path: /jsonInfo
    data-path: /jsonData
  job:
    name: JOB (pro)
  json:
    name: JSON (pro)
    error-info-file: error.json
  url:
    name: URL (pro)
    #sentbe: http://localhost:17080/v0.6
    sentbe: https://hanwha.dev.sentbe.com:10443

---
# --------------------------------------------------------
# proj-aws
spring.profiles: proj-aws

proj-env:
  param:
    name: PARAM (aws)
  job:
    name: JOB (aws)
  json:
    name: JSON (aws)
  url:
    name: URL (aws)

---
# --------------------------------------------------------
# proj-dfep
spring.profiles: proj-dfep

proj-env:

  param:
    name: PARAM (dfep)
    sentbe-client-key: Jien4aeyae7ohjeithahM9ja7quowua4
    sentbe-secret-key-for-data: cXdqZmlvcWVqd2xd2pmam9pZaG9nZnFl
    sentbe-secret-key-for-hmac: 6fc1bf16f3cb6f5b6a1044fd9edecba9722014489c39a7d16ad7b9961aea770b9cd0e3e4a85510bba0dd97e6d6aac884d910e6384c7b76df992deece5cb57a78
    home: /hw01/ibridge
    base: /KANG/sentbe/20201010
    info-path: /jsonInfo
    data-path: /jsonData
  job:
    name: JOB (dfep)
  json:
    name: JSON (dfep)
    error-info-file: error.json
  url:
    name: URL (dfep)
    #sentbe: http://localhost:17080/v0.6      # vSentbe
    sentbe: http://10.200.50.4:10443          # VPN of Sentbe for DEV
    #sentbe: https://hanwha.dev.sentbe.com:10443

---
# --------------------------------------------------------
# proj-real
spring.profiles: proj-real

proj-env:
  param:
    name: PARAM (real)
  job:
    name: JOB (real)
  json:
    name: JSON (real)
  url:
    name: URL (real)
    #sentbe: https://hanwha.sentbe.com:10443
    sentbe: https://10.200.50.1:11443         # VPN of Sentbe for REAL
    #sentbe: https://10.200.50.2:11443         # NODE-1: VPN of Sentbe for REAL
    #sentbe: https://10.200.50.3:11443         # NODE-2: VPN of Sentbe for REAL


